#!/usr/bin/env bash

echo -e 'db.host='${SQL_HOST}'\ndb.user='${SQL_USER}'\ndb.password='${SQL_PASSWORD} > /root/.hg.conf
chmod 600 /root/.hg.conf

rm -f /var/www/cgi-bin/hg.conf && cp -f /opt/kent/src/product/ex.hg.conf /var/www/cgi-bin/hg.conf
sed -i 's/defaultGenome=.*/defaultGenome='"$DEFAULTGENOME"'/g' /var/www/cgi-bin/hg.conf
sed -i 's/wiki\.host=.*/wiki\.host=HTTPHOST/g' /var/www/cgi-bin/hg.conf
sed -i 's/central\.domain=.*/central\.domain=HTTPHOST/g' /var/www/cgi-bin/hg.conf
sed -i 's/central\.host=.*/central\.host='"$SQL_HOST"'/g' /var/www/cgi-bin/hg.conf
sed -i 's/db\.host=.*/db\.host='"$SQL_HOST"'/g' /var/www/cgi-bin/hg.conf
sed -i 's/login\.browserName=.*/login\.browserName='"$BROWSERNAME"'/g' /var/www/cgi-bin/hg.conf
sed -i 's/login\.browserAddr=.*/login\.browserAddr=http:\/\/'"${HOSTNAME}.${DOMAIN}"'/g' /var/www/cgi-bin/hg.conf
sed -i 's/login\.mailSignature=Greenome Browser Staff=.*/login\.mailSignature=Greenome Browser Staff/g' /var/www/cgi-bin/hg.conf
sed -i 's/login\.mailReturnAddr=.*/login\.mailReturnAddr='"$WIKIEMAIL"'/g' /var/www/cgi-bin/hg.conf
sed -i 's/custromTracks\.host=.*/custromTracks\.host=localhost/g' /var/www/cgi-bin/hg.conf
sed -i 's/customTracks\.host=.*/customTracks\.host='"$SQL_HOST"'/g' /var/www/cgi-bin/hg.conf
sed -i 's/customTracks\.user=.*/customTracks\.user=readwrite/g' /var/www/cgi-bin/hg.conf
sed -i 's/customTracks\.password=.*/customTracks\.password=update/g' /var/www/cgi-bin/hg.conf
sed -i 's#customTracks\.tmpdir=.*#customTracks\.tmpdir='/var/www/trash/ct'#g' /var/www/cgi-bin/hg.conf
sed -i 's#browser.documentRoot=.*#browser.documentRoot='/var/www'#g' /var/www/cgi-bin/hg.conf



curl -sL "https://spreadsheets.google.com/feeds/download/spreadsheets/Export?key="$DBDBID"&hl=en&exportFormat=tsv" | \
 tr -d "\r" > /tmp/dbDb.tsv && echo "" >> /tmp/dbDb.tsv

# make assembly html files #######
cols=$(head -n 1 /tmp/dbDb.tsv) && \
 tail -n+2 /tmp/dbDb.tsv | while IFS=$'\t' read -r $cols
 do
  mkdir $htmlPath
  if [ "$summary" != "NA" ]; then
    echo "<br> $summary <br><hr>" > $htmlPath
  fi
  if [ "$credits" != "NA" ]; then
    echo "<h2>Credits</h2> $credits <hr>" >> $htmlPath
  fi
 done
